apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: kube-system   # HelmChart ต้องอยู่ kube-system
spec:
  chart: gitea
  version: 2.2.0
  repo: https://dl.gitea.io/charts/
  targetNamespace: gitea

  valuesContent: |-
    gitea:
      admin:
        username: <<GIT_USER>>
        password: <<GIT_PASSWORD>>
        email: <<GIT_EMAIL>>

      config:
        server:
          ROOT_URL: http://gitea.gitea.svc.cluster.local:3000
          DOMAIN: gitea.gitea.svc.cluster.local
          HTTP_PORT: 3000
  
    service:
      http:
        type: ClusterIP
        port: 3000

    ingress:
      enabled: false

    persistence:
      enabled: true
      size: 5Gi
