filebeat.config.modules:
  path: /filebeat-modules/module.yaml
  reload.enabled: false
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
output.logstash:
  hosts: ["server:5044"]
